apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mysql
  template:
    metadata:
      labels:
        app: auth-mysql
    spec:
      containers:
        - name: auth-mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "authdb"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: auth-mysql-storage
      volumes:
        - name: auth-mysql-storage
          persistentVolumeClaim:
            claimName: auth-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql
spec:
  selector:
    app: auth-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
